### ISSUE TITLE
validates_datetime problem with Time.now

### ISSUE THREAD

**Issue by denispolicarpocampos** [adzap/validates_timeliness#155]
I have a datatime and I'm trying to set in my models that the user can only choose datatime greater than or equal to today's datatime. I am using the validates_timeliness gem as follows:

validates_datetime :data, :on_or_after => lambda { Time.now }
But when I fill in the form with the date it only accepts if a datatime is assigned with 3 hours more than the current datatime. My version is 5.0.2

Can anyone help?

**Comment by adzap** [comment]
Try using Time.current instead. Though you will need to set the user’s timezone otherwise Time.current will return the app default timezone.

On Tue, May 23, 2017 at 2:10 AM, denispolicarpocampos <notifications@github.com> wrote:
I have a datatime and I'm trying to set in my models that the user can only choose datatime greater than or equal to today's datatime. I am using the validates_timeliness gem as follows:

validates_datetime :data, :on_or_after => lambda { Time.now }
But when I fill in the form with the date it only accepts if a datatime is assigned with 3 hours more than the current datatime. My version is 5.0.2

Can anyone help?
