### ISSUE TITLE
I18n in custom validation message fails

### ISSUE THREAD

**Issue by trooster** [adzap/validates_timeliness#157]
In my model I need a custom validation message. I have defined it like this:

`  validates :starts_on, timeliness: {`
`    type: :date,`
`    on_or_after: lambda { |c| c.unit.starts_on },`
`    if: lambda { |c| c.unit }, # in case the unit is not yet set, skip validation`
`    on_or_after_message: I18n.t("errors.messages.must_be_after_unit_start_date")`
`  }`

However, the I18n is causing problems. It caches the first request language and uses the same language on future requests.

**Comment by adzap** [comment]
You have used the I18n call at the class level. So that translation is evaluated once on boot, not once per validation. That is not something to do with the gem but just how to understand that class level validations are evaluated once.
To allow this message to be evaluated at validation time you need to move the message into each languages translation file. I suggest reviewing how and where ActiveRecord I18n messages are to be defined. The Rails guides will probably be of some help, then review this README for the gem to understand where to put i18n message definitions.




On Tue, Aug 1, 2017 at 12:50 AM, Joris Trooster <notifications@github.com> wrote:
In my model I need a custom validation message. I have defined it like this:

validates :starts_on, timeliness: {
type: :date,
on_or_after: lambda { |c| c.unit.starts_on },
if: lambda { |c| c.unit }, # in case the unit is not yet set, skip validation
on_or_after_message: I18n.t("errors.messages.must_be_after_unit_start_date")
}

However, the I18n is causing problems. It caches the first request language and uses the same language on future requests.
