### ISSUE TITLE
Issue on engine test load

### ISSUE THREAD

**Issue by EQuincerot** [adzap/validates_timeliness#208]
Since 7fa4d85ee37a18 our factories (using factory_bot) are no longer loaded when they are located in engines.

Before this commit we go through these steps:
```
Loading lib/engines.rb
Loading gems/validates_timeliness/railtie.rb initializer
Load_config_initializer
Loading factory_bot_rails/railtie.rb
Loading engines/***/test/factories/***
```

After this commit, we have this:
```
Loading lib/engines.rb
Load_config_initializer
Loading gems/validates_timeliness/railtie.rb initializer
Loading factory_bot_rails/railtie.rb
```
Because of that, our engines factories are not loaded.

Do you know why this small change could impact the way factories in our engines are loaded?

**Comment by adzap** [comment]
I'm sorry I don't have a clue. The steps you list above, are they the order of steps initialisation during Rails boot? 

You can see that the `validates_timeliness` initializer was being loaded in the wrong order hence the this change. It should occur after `load_config_initializers` and does now, since this change.

I don't know how your engine factories were being loaded to begin with. Do you add a path to factory bot to load them during its initialization?

**Comment by EQuincerot** [comment]
After further investigation, I finally managed to change the way our engines were declared to factory bot.
The engine paths were overridden to early.
We now use `Rails.configuration.to_prepare` and it works well.

Sorry for the noise, and thanks for your help ;)
